# Stage 1: build a custom runtime image
FROM openjdk:9-jdk as image-runtime-build

COPY target/jmods/*.jmod .
RUN jlink --module-path /usr/lib/jvm/java-9-openjdk-amd64/jmods:. \
	--compress 2 \
	--no-header-files \
	--no-man-pages \
	--dedup-legal-notices=error-if-not-same-content \
	--strip-debug \
	--vm=server \
	--exclude-jmod-section=man \
	--exclude-jmod-section=headers \
	--add-modules tech.barbero.contained.java.example \
	--output /runtime

RUN rm -f ./runtime/lib/java_*.properties

# Stage 2: create distroless docker image

FROM mbarbero/distroless-openjdk-official

COPY --from=image-runtime-build runtime/ /app

ENTRYPOINT [ "/app/bin/java", "-m", "tech.barbero.contained.java.example/tech.barbero.contained.java.example.Main" ] 